Fix formatting block
Fixed the formatting block in `base_layer/mmr/src/sparse_merkle_tree/mod.rs`

This caused a formatting warp, but sufficiently excluded the text from doc tests:
//! .           ┌──────┐

This fixed the formatting warp, but added the text to the doc test, which failed:
//!             ┌──────┐
Test error:
as
---- src\sparse_merkle_tree\mod.rs - sparse_merkle_tree (line 28) stdout ----
error: unknown start of token: \u{250c}
 --> src\sparse_merkle_tree\mod.rs:29:1
  |
3 | ┌──────┐
  | ^

This fixed both issues:
//! r###"                     ┌──────┐                            "###