fix latent transaction service unit test errors (#4595)
Description
---
Fixed latent transaction service unit test errors

Motivation and Context
---
Some failing tests due to recent coinbase handling logic changes:
```
failures:

---- transaction_service_tests::service::test_coinbase_transaction_reused_for_same_height stdout ----
thread 'transaction_service_tests::service::test_coinbase_transaction_reused_for_same_height' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', base_layer/wallet/tests/transaction_service_tests/service.rs:3968:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- transaction_service_tests::service::test_coinbase_generation_and_monitoring stdout ----
thread 'transaction_service_tests::service::test_coinbase_generation_and_monitoring' panicked at 'assertion failed: `(left == right)`
  left: `Coinbase`,
 right: `MinedUnconfirmed`', base_layer/wallet/tests/transaction_service_tests/service.rs:3405:5

---- transaction_service_tests::service::test_transaction_resending stdout ----
thread 'transaction_service_tests::service::test_transaction_resending' panicked at 'assertion failed: alice_ts_interface.outbound_service_mock_state.wait_call_count(1,\n            Duration::from_secs(5)).await.is_err()', base_layer/wallet/tests/transaction_service_tests/service.rs:4181:5


failures:
    transaction_service_tests::service::test_coinbase_generation_and_monitoring
    transaction_service_tests::service::test_coinbase_transaction_reused_for_same_height
    transaction_service_tests::service::test_transaction_resending

test result: FAILED. 39 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 107.87s
```

How Has This Been Tested?
---
Failing uni tests passed