Mention Protobuf dependencies
Hi,

Installing protobuf depdendencies will help to prevent compilation error:

```
Compiling synstructure v0.12.3
error: failed to run custom build command for `prost-build v0.6.1`

Caused by:
  process didn't exit successfully: `/mnt/ext/tari-src/target/release/build/prost-build-567322a74cee75bf/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to find the protoc binary. The PROTOC environment variable is not set, there is no bundled protoc for this platform, and protoc is not in the PATH', src/libcore/option.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

OS: Debian GNU/Linux 10 (buster)