feat: fix formatting block (#5630)
Description
---
Fixed the formatting block in
`base_layer/mmr/src/sparse_merkle_tree/mod.rs`

This caused a formatting warp, but sufficiently excluded the text from
doc tests:
```
//! .           ┌──────┐
```

This fixed the formatting warp, but added the text to the doc test,
which failed:
```
//!             ┌──────┐
```
Test error:
```
as
---- src\sparse_merkle_tree\mod.rs - sparse_merkle_tree (line 28) stdout ----
error: unknown start of token: \u{250c}
 --> src\sparse_merkle_tree\mod.rs:29:1
  |
3 | ┌──────┐
  | ^
```

This fixed both issues:
```
//! r###"                     ┌──────┐                            "###
```

Motivation and Context
---
See above

How Has This Been Tested?
---
Ran `rust update`, then `cargo +nightly fmt --all` and then `cargo test
--release`

What process can a PR reviewer use to test or verify this change?
---
Run `rust update`, then `cargo +nightly fmt --all` and then `cargo test
--release`

<!-- Checklist -->
<!-- 1. Is the title of your PR in the form that would make nice release
notes? The title, excluding the conventional commit
tag, will be included exactly as is in the CHANGELOG, so please think
about it carefully. -->


Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

<!-- Does this include a breaking change? If so, include this line as a
footer -->
<!-- BREAKING CHANGE: Description what the user should do, e.g. delete a
database, resync the chain -->