test: turn off multiplexing for cargo on cucumber (#3533)
Description
---

Turn off [http multiplexing](https://doc.rust-lang.org/cargo/reference/config.html#httpmultiplexing) for cargo on the integration tests. 

Trying to resolve spurious network errors 

```
warning: spurious network error (1 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 201 was not closed cleanly before end of the underlying stream)
error: failed to download from `https://crates.io/api/v1/crates/rsa/0.3.0/download`

Caused by:
  [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 203 was not closed cleanly before end of the underlying stream)
``` 

Reference: https://github.com/rust-lang/cargo/issues/6513#issuecomment-920920238